/* Parla — conversation scenarios & tutor settings (classic script; shares globals with the other js/ files, load order matters) */
/* ----------------------------------------------------------------------------
   Parla — voice-only Italian tutor.  Browser does the listening (speech
   recognition) and the talking (speech synthesis); Claude does the thinking.
---------------------------------------------------------------------------- */

const DEFAULT_MODEL = "anthropic/claude-sonnet-4.5";  // accurate Italian + translations. Switch to ⚡ Faster (haiku) in the header.
const MAX_TURNS = 12;                                 // messages of history sent each turn (6 exchanges) — keeps replies fast and cheap

// Scenarios. "scene" steers the tutor's role; "opener" is Giulia's first line.
const TOPICS = {
  free:        { scene:"", opener:{ reply_it:"Ciao! Sono Giulia. Di cosa ti piacerebbe parlare oggi?", hint:"Hi! I'm Giulia. What would you like to talk about today?" } },
  ristorante:  { scene:"Role-play: you are a friendly waiter at an Italian restaurant; the student is a customer having dinner. Arc: greet & seat them → take the food and drink order → check on the meal → offer dessert or coffee → the bill & goodbye. Twist to spring mid-scene: the dish they ordered has just run out (suggest today's special), or recommend something unexpected.", opener:{ reply_it:"Buonasera e benvenuto! Ha già scelto o le porto il menù?", hint:"Good evening and welcome! Have you chosen, or shall I bring you the menu?" } },
  bar:         { scene:"Role-play: you are a barista at a busy Italian bar/café; the student is a customer. Arc: greet → take the drink order → offer something to eat → a little small talk about their day or plans → they pay & goodbye. Twist to spring mid-scene: the cornetti have just sold out (offer an alternative), or ask if they'll have it at the counter or at a table — the price differs!", opener:{ reply_it:"Buongiorno! Cosa le porto da bere?", hint:"Good morning! What can I get you to drink?" } },
  shopping:    { scene:"Role-play: you are a shop assistant; the student is shopping for clothes or a gift. Arc: greet → find out what they need → sizes, colours, preferences → they try it / consider it → price & paying → goodbye. Twist to spring mid-scene: their size is out of stock (offer another colour or model), or there's a 2-for-1 offer they must decide on.", opener:{ reply_it:"Buongiorno! Posso aiutarla a trovare qualcosa?", hint:"Good morning! Can I help you find something?" } },
  stazione:    { scene:"Role-play: you work at the ticket counter of an Italian train station; the student needs to travel. Arc: destination → departure times → ticket type (single/return, class) → price & platform → goodbye. Twist to spring mid-scene: the direct train is delayed or cancelled — offer an alternative with a change at Bologna and see how they cope.", opener:{ reply_it:"Buongiorno! Dove desidera andare oggi?", hint:"Good morning! Where would you like to go today?" } },
  indicazioni: { scene:"Role-play: you are a friendly local in an Italian town; the student is lost and needs directions. Arc: find out where they're going → give simple directions with landmarks → check they've understood (ask them to repeat the route back!) → wish them well. Twist to spring mid-scene: the usual road is closed for a street market — reroute them, or walk part of the way together chatting.", opener:{ reply_it:"Certo, posso aiutarla! Dove deve andare?", hint:"Of course, I can help! Where do you need to go?" } },

  /* ---- Grammar practice · A1 — everyday-Italy conversations that force the target grammar ---- */
  g_presente:   { scene:"Grammar coaching: PRESENT INDICATIVE (regular verbs + essere/avere). Setting: chatting with a new Italian friend about daily life — where the student lives, works, eats, what they do each day. Ask questions that require io/tu forms (abito, lavoro, mangio, sono, ho). When they misconjugate, model the right form and invite them to retry.", opener:{ reply_it:"Parliamo della tua giornata! Dove abiti e cosa fai ogni giorno?", hint:"Let's talk about your day! Where do you live and what do you do every day?" } },
  g_modali:     { scene:"Grammar coaching: MODAL VERBS in the present (potere, dovere, volere). Setting: the student is a guest at an Italian hotel asking what they can do, must do, and want to do (Posso pagare…? Devo lasciare la chiave? Voglio prenotare…). Ask questions that force posso/devo/voglio and their tu/Lei forms.", opener:{ reply_it:"Benvenuto in hotel! Cosa vuole fare oggi: vuole visitare la città?", hint:"Welcome to the hotel! What do you want to do today — do you want to visit the city?" } },
  g_imperativo: { scene:"Grammar coaching: IMPERATIVE (tu, Lei, noi). Setting: exchanging instructions and directions in town — the student both receives directions (Vada dritto, giri a destra) and gives them (Prendi la prima a sinistra). Have them practise polite Lei commands and friendly tu commands.", opener:{ reply_it:"Facciamo pratica con le indicazioni! Come arrivo alla stazione? Dimmi tu!", hint:"Let's practise directions! How do I get to the station? You tell me!" } },
  g_vorrei:     { scene:"Grammar coaching: SIMPLE CONDITIONAL for politeness (vorrei, mi piacerebbe, potrebbe). Setting: ordering and requesting things politely around town — café, gelateria, shop, pharmacy. Encourage 'vorrei un…', 'potrebbe darmi…?' instead of blunt forms; contrast voglio vs vorrei.", opener:{ reply_it:"Buongiorno! Sono la barista. Cosa vorrebbe ordinare oggi?", hint:"Good morning! I'm the barista. What would you like to order today?" } },
  g_cessere:    { scene:"Grammar coaching: C'È / CI SONO. Setting: the student has just arrived in a small Italian town and asks what there is — C'è una farmacia? Ci sono ristoranti? You answer as a local and ask them what there is in their own town, forcing both singular and plural.", opener:{ reply_it:"Benvenuto nel mio paese! Cosa vuoi sapere: c'è qualcosa che cerchi?", hint:"Welcome to my town! What do you want to know — is there something you're looking for?" } },
  g_articoli:   { scene:"Grammar coaching: DEFINITE & INDEFINITE ARTICLES (il/lo/la/i/gli/le, un/uno/una). Setting: shopping at an Italian open-air market — naming fruits, vegetables, items with the right article (il pane, la mela, gli spinaci, un'arancia). Gently drill gender/number through what they buy.", opener:{ reply_it:"Benvenuto al mercato! Cosa le serve oggi: la frutta o la verdura?", hint:"Welcome to the market! What do you need today — fruit or vegetables?" } },
  g_riflessivi: { scene:"Grammar coaching: PERSONAL & REFLEXIVE PRONOUNS (mi alzo, mi lavo, ti svegli). Setting: comparing morning and evening routines with a friend. Ask what time they wake up, get dressed, relax — forcing reflexive forms, and share yours back.", opener:{ reply_it:"Parliamo delle abitudini! A che ora ti svegli la mattina?", hint:"Let's talk about habits! What time do you wake up in the morning?" } },
  g_domande:    { scene:"Grammar coaching: INTERROGATIVES (chi, cosa, dove, quando, perché, quanto, quale, come). Setting: the student is a curious tourist interviewing a local (you) about the town, food and festivals. Push them to ask varied questions; correct malformed ones and have them re-ask.", opener:{ reply_it:"Sono del posto: chiedimi tutto sulla mia città! Cosa vuoi sapere?", hint:"I'm a local — ask me anything about my town! What do you want to know?" } },
  g_preposizioni:{ scene:"Grammar coaching: SIMPLE & ARTICULATED PREPOSITIONS (a, in, di, da, su + articles: al, alla, nel, sulla…). Setting: describing where things are in town and how to move between them — Vado al bar, il museo è nella piazza. Ask where things are in their town too.", opener:{ reply_it:"Dove andiamo oggi? Al bar, alla stazione o nel centro storico?", hint:"Where shall we go today? To the bar, the station, or the old town?" } },
  g_aggettivi:  { scene:"Grammar coaching: ADJECTIVES (qualifiers, possessives, demonstratives, numerals) with agreement. Setting: describing things while shopping and talking about family — questa giacca rossa, il mio fratello alto, due caffè. Push agreement in gender and number; correct mismatches.", opener:{ reply_it:"Descrivimi qualcosa! Com'è la tua casa o la tua famiglia?", hint:"Describe something to me! What is your house or your family like?" } },
  g_avverbi:    { scene:"Grammar coaching: ADVERBS of manner, place and time (bene, male, spesso, sempre, qui, lì, presto, tardi). Setting: chatting about habits and lifestyle in Italy — how often they do things, when, and how well. Ask questions that elicit adverbs and offer better ones.", opener:{ reply_it:"Quanto spesso mangi fuori: sempre, spesso o quasi mai?", hint:"How often do you eat out — always, often, or almost never?" } },
  g_negazione:  { scene:"Grammar coaching: NEGATION & YES/NO QUESTIONS (non, non…mai, non…niente, nessuno). Setting: at a tourist information desk sorting out misunderstandings — the student confirms and denies things (No, non ho una prenotazione; Non mangio mai carne). Ask yes/no questions they must answer in full sentences.", opener:{ reply_it:"Ufficio turistico, buongiorno! Ha una prenotazione con noi?", hint:"Tourist office, good morning! Do you have a booking with us?" } },

  /* ---- Grammar practice · A2 ---- */
  g_passato:    { scene:"Grammar coaching: PASSATO PROSSIMO vs IMPERFETTO. Setting: telling a friend about yesterday and about a recent trip in Italy — what happened (sono andato, ho mangiato) versus how things were (era bello, c'era il sole, faceva caldo). Ask follow-ups that force both tenses and highlight the contrast when correcting.", opener:{ reply_it:"Raccontami di ieri! Cosa hai fatto e com'era la giornata?", hint:"Tell me about yesterday! What did you do, and what was the day like?" } },
  g_futuro:     { scene:"Grammar coaching: SIMPLE FUTURE (andrò, farò, sarà). Setting: planning the student's next weekend or next trip to Italy — where they will go, what they will see and eat. Push future forms; when they slip into the present, model the future version.", opener:{ reply_it:"Facciamo progetti! Cosa farai il prossimo fine settimana?", hint:"Let's make plans! What will you do next weekend?" } },
  g_reciproci:  { scene:"Grammar coaching: REFLEXIVE & RECIPROCAL VERBS (vedersi, incontrarsi, sentirsi, aiutarsi). Setting: talking about friendships and meeting people in Italy — Ci vediamo domani? Vi sentite spesso? Elicit ci/vi/si forms about the student's friends and family.", opener:{ reply_it:"Parliamo di amici! Tu e i tuoi amici vi vedete spesso?", hint:"Let's talk about friends! Do you and your friends see each other often?" } },
  g_clitici:    { scene:"Grammar coaching: CLITIC & TONIC PRONOUNS (lo, la, li, le, gli, le, ne; me, te). Setting: at a shop deciding what to buy — Lo prendo! La vuole? Ne prendo due. Ask questions whose natural answers need object pronouns, and recast their answers with the pronoun when they avoid it.", opener:{ reply_it:"Le piace questa borsa? La prende o vuole vederne un'altra?", hint:"Do you like this bag? Will you take it, or do you want to see another one?" } },
  g_possessivi: { scene:"Grammar coaching: POSSESSIVE & DEMONSTRATIVE PRONOUNS (il mio, la tua, questo, quello). Setting: comparing belongings and choices in a clothes shop — Questo è il mio, quello è più bello. Elicit questo/quello contrasts and possessives with and without nouns.", opener:{ reply_it:"Guarda queste giacche: preferisci questa qui o quella lì?", hint:"Look at these jackets: do you prefer this one here or that one there?" } },
  g_relativi:   { scene:"Grammar coaching: INDEFINITE & RELATIVE PRONOUNS (che, cui, chi, qualcosa, qualcuno, niente). Setting: describing people and places — Il ristorante che preferisco, la città in cui vivo, qualcuno che conosco. Ask for descriptions that require che/cui and indefinite pronouns.", opener:{ reply_it:"Descrivimi un posto che ami e una persona che conosci bene!", hint:"Describe to me a place you love and a person you know well!" } },
  g_partitivo:  { scene:"Grammar coaching: PARTITIVE ARTICLES (del, della, dei, delle; un po' di). Setting: food shopping at an alimentari for a picnic — Vorrei del pane, delle olive, un po' di formaggio. You are the shopkeeper; ask what they need until they've 'bought' a full picnic using partitives.", opener:{ reply_it:"Buongiorno! Prepara un picnic? Cosa le do: del pane, del formaggio?", hint:"Good morning! Preparing a picnic? What shall I get you — some bread, some cheese?" } },
  g_geotempo:   { scene:"Grammar coaching: ARTICLES with GEOGRAPHIC NAMES & TIME EXPRESSIONS (in Italia, a Roma, la Sicilia, il lunedì, in estate, alle otto). Setting: planning a tour of Italy through the seasons — regions, cities, days and times. Correct missing/wrong articles with places and times.", opener:{ reply_it:"Organizziamo un viaggio in Italia! In quale regione vuoi andare e in quale stagione?", hint:"Let's plan a trip in Italy! Which region do you want to go to, and in which season?" } },
  g_comparativi:{ scene:"Grammar coaching: COMPARATIVES & SUPERLATIVES (più…di, meno…che, il più, buonissimo, migliore/peggiore). Setting: friendly debate comparing Italian cities, foods and coffee — Roma è più grande di Firenze, il gelato migliore. Provoke comparisons and superlatives with fun either/or questions.", opener:{ reply_it:"Secondo te, è più bella Roma o Venezia? E qual è il cibo italiano migliore?", hint:"In your opinion, is Rome or Venice more beautiful? And what's the best Italian food?" } },
  g_prepavanzate:{ scene:"Grammar coaching: PREPOSITIONS of possession, origin, manner and quantity (di Maria, vengo da Londra, di fretta, un chilo di mele). Setting: introducing yourself at a market and doing the shopping — where you're from, whose things are whose, and quantities (un etto di, mezzo chilo di). Elicit di/da/a in these roles.", opener:{ reply_it:"Buongiorno! Di dove sei? E cosa ti serve oggi: un chilo di pomodori?", hint:"Good morning! Where are you from? And what do you need today — a kilo of tomatoes?" } },
};
